create database KB_Portfolio_Toronto_Fires;

use KB_Portfolio_Toronto_Fires;

/* The schema for this database was designed using dbdiagram.io 
   The majority of the below code is generated by dbdiagram.io, based on the schema I designed using it */

CREATE TABLE `fire_details` (
  `id` varchar(15) PRIMARY KEY,
  `area_of_origin_fk` varchar(5) default null,
  `level_of_origin` varchar(5) default null,
  `exposure_fires` varchar(5) default null,
  `extent_of_fire_fk` varchar(5) default null,
  `final_incident_type_fk` varchar(5),
  `ignition_source_fk` varchar(5) default null,
  `material_first_ignited_fk` varchar(5) default null,
  `possible_cause_fk` varchar(5) default null,
  `smoke_spread_fk` varchar(5) default null,
  `status_fire_on_arrival_fk` varchar(5) default null
);

CREATE TABLE `smoke_alarms` (
  `id` varchar(15) PRIMARY KEY,
  `sa_fire_origin_fk` varchar(5) default null,
  `sa_failure_fk` varchar(5) default null,
  `sa_type_fk` varchar(5) default null,
  `sa_impact_evacuation_fk` varchar(5) default null
);

CREATE TABLE `fire_alarms` (
  `id` varchar(15) PRIMARY KEY,
  `impact_evacuation_fk` varchar(5) default null,
  `fa_operation_fk` varchar(5) default null,
  `fa_pesence_fk` varchar(5) default null
);

CREATE TABLE `sprinkler_systems` (
  `id` varchar(15) PRIMARY KEY,
  `sp_operation_fk` varchar(5) default null,
  `sp_presence_fk` varchar(5) default null
);

CREATE TABLE `civilian_impact` (
  `id` varchar(15) PRIMARY KEY,
  `casualties` integer default 0,
  `people_rescued` integer default 0,
  `est_people_displaced` integer default 0
);

CREATE TABLE `damages` (
  `id` varchar(15) PRIMARY KEY,
  `building_status_fk` varchar(5) default null,
  `business_impact_fk` varchar(5) default null,
  `est_dollar_loss` integer default 0
);

CREATE TABLE `toronto_fire_services` (
  `id` varchar(15) PRIMARY KEY,
  `agent_app_deferred` datetime not null,
  `initial_cad_event_fk` varchar(5) default null,
  `method_fire_control_fk` varchar(5) default null,
  `responding_apparatus` integer default 0,
  `responding_personnel` integer default 0,
  `tfs_alarm_time` datetime not null,
  `tfs_arrival_time` datetime not null,
  `fire_controlled_time` datetime not null,
  `last_tfs_unit_clear_time` datetime not null,
  `firefighter_casualties` integer default 0
);

CREATE TABLE `location` (
  `id` varchar(15) PRIMARY KEY,
  `incident_station_area` integer not null,
  `incident_ward` integer not null,
  `intersection` varchar(500) not null,
  `latitude` double not null,
  `longitude` double not null,
  `property_use_fk` varchar(5) default null
);

CREATE TABLE `fire_alarms_system_impact` (
  `id` varchar(5) PRIMARY KEY,
  `fasi_desc` varchar(500) not null
);

CREATE TABLE `fire_alarms_system_operation` (
  `id` varchar(5) PRIMARY KEY,
  `faso_desc` varchar(500) not null
);

CREATE TABLE `final_incident_type` (
  `id` varchar(5) PRIMARY KEY,
  `incident_type_desc` varchar(300) not null
);

CREATE TABLE `fire_alarms_system_presence` (
  `id` varchar(5) PRIMARY KEY,
  `fasp_desc` varchar(500) not null
);

CREATE TABLE `ignition_source` (
  `id` varchar(5) PRIMARY KEY,
  `ignition_des` varchar(500) not null
);

CREATE TABLE `initial_cad_event` (
  `id` varchar(5) PRIMARY KEY,
  `cad_desc` varchar(500) not null
);

CREATE TABLE `material_first_ignited` (
  `id` varchar(5) PRIMARY KEY,
  `mfi_desc` varchar(500) not null
);

CREATE TABLE `method_fire_control` (
  `id` varchar(5) PRIMARY KEY,
  `mfc_desc` varchar(500) not null
);

CREATE TABLE `possible_cause` (
  `id` varchar(5) PRIMARY KEY,
  `pc_desc` varchar(500) not null
);

CREATE TABLE `property_use` (
  `id` varchar(5) PRIMARY KEY,
  `property_use_desc` varchar(500) not null
);

CREATE TABLE `smoke_alarm_at_fire_origin` (
  `id` varchar(5) PRIMARY KEY,
  `sa_desc` varchar(500) not null
);

CREATE TABLE `smoke_alarm_at_fire_origin_failure` (
  `id` varchar(5) PRIMARY KEY,
  `sa_failure_desc` varchar(500) not null
);

CREATE TABLE `smoke_alarm_at_fire_origin_alarm_type` (
  `id` varchar(5) PRIMARY KEY,
  `sa_type_desc` varchar(500) not null
);

CREATE TABLE `smoke_alarm_impact_evacuation` (
  `id` varchar(5) PRIMARY KEY,
  `sa_imp_evac_desc` varchar(500) not null
);

CREATE TABLE `smoke_spread` (
  `id` varchar(5) PRIMARY KEY,
  `smoke_spread_desc` varchar(500) not null
);

CREATE TABLE `sprinkler_system_operation` (
  `id` varchar(5) PRIMARY KEY,
  `spo_desc` varchar(500) not null
);

CREATE TABLE `sprinkler_system_presence` (
  `id` varchar(5) PRIMARY KEY,
  `spp_desc` varchar(500) not null
);

CREATE TABLE `status_fire_on_arrival` (
  `id` varchar(5) PRIMARY KEY,
  `sfa_desc` varchar(500) not null
);

CREATE TABLE `area_of_origin` (
  `id` varchar(5) PRIMARY KEY,
  `aoo_desc` varchar(500) not null
);

CREATE TABLE `building_status` (
  `id` varchar(5) PRIMARY KEY,
  `building_status_desc` varchar(500) not null
);

CREATE TABLE `business_impact` (
  `id` varchar(5) PRIMARY KEY,
  `building_impact_desc` varchar(500) not null
);

CREATE TABLE `extent_of_fire` (
  `id` varchar(5) PRIMARY KEY,
  `eof_desc` varchar(500) not null
);

CREATE TABLE `incidents_fact_table` (
  `id` varchar(15) PRIMARY KEY,
  `date` date not null,
  `fire_details_fk` varchar(15),
  `tfs_fk` varchar(15),
  `location_fk` varchar(15),
  `civilian_impact_fk` varchar(15),
  `sprinkler_systems_fk` varchar(15),
  `smoke_alarms_fk` varchar(15),
  `fire_alarms_fk` varchar(15),
  `damages_fk` varchar(15)
);


ALTER TABLE `fire_details` ADD FOREIGN KEY (`extent_of_fire_fk`) REFERENCES `extent_of_fire` (`id`);

ALTER TABLE `fire_details` ADD FOREIGN KEY (`area_of_origin_fk`) REFERENCES `area_of_origin` (`id`);

ALTER TABLE `fire_details` ADD FOREIGN KEY (`ignition_source_fk`) REFERENCES `ignition_source` (`id`);

ALTER TABLE `fire_details` ADD FOREIGN KEY (`final_incident_type_fk`) REFERENCES `final_incident_type` (`id`);

ALTER TABLE `fire_details` ADD FOREIGN KEY (`material_first_ignited_fk`) REFERENCES `material_first_ignited` (`id`);

ALTER TABLE `fire_details` ADD FOREIGN KEY (`possible_cause_fk`) REFERENCES `possible_cause` (`id`);

ALTER TABLE `fire_details` ADD FOREIGN KEY (`smoke_spread_fk`) REFERENCES `smoke_spread` (`id`);

ALTER TABLE `fire_details` ADD FOREIGN KEY (`status_fire_on_arrival_fk`) REFERENCES `status_fire_on_arrival` (`id`);

ALTER TABLE `toronto_fire_services` ADD FOREIGN KEY (`initial_cad_event_fk`) REFERENCES `initial_cad_event` (`id`);

ALTER TABLE `toronto_fire_services` ADD FOREIGN KEY (`method_fire_control_fk`) REFERENCES `method_fire_control` (`id`);

ALTER TABLE `fire_alarms` ADD FOREIGN KEY (`fa_pesence_fk`) REFERENCES `fire_alarms_system_presence` (`id`);

ALTER TABLE `fire_alarms` ADD FOREIGN KEY (`fa_operation_fk`) REFERENCES `fire_alarms_system_operation` (`id`);

ALTER TABLE `fire_alarms` ADD FOREIGN KEY (`impact_evacuation_fk`) REFERENCES `fire_alarms_system_impact` (`id`);

ALTER TABLE `damages` ADD FOREIGN KEY (`building_status_fk`) REFERENCES `building_status` (`id`);

ALTER TABLE `damages` ADD FOREIGN KEY (`business_impact_fk`) REFERENCES `business_impact` (`id`);

ALTER TABLE `smoke_alarms` ADD FOREIGN KEY (`sa_impact_evacuation_fk`) REFERENCES `smoke_alarm_impact_evacuation` (`id`);

ALTER TABLE `smoke_alarms` ADD FOREIGN KEY (`sa_type_fk`) REFERENCES `smoke_alarm_at_fire_origin_alarm_type` (`id`);

ALTER TABLE `smoke_alarms` ADD FOREIGN KEY (`sa_failure_fk`) REFERENCES `smoke_alarm_at_fire_origin_failure` (`id`);

ALTER TABLE `smoke_alarms` ADD FOREIGN KEY (`sa_fire_origin_fk`) REFERENCES `smoke_alarm_at_fire_origin` (`id`);

ALTER TABLE `sprinkler_systems` ADD FOREIGN KEY (`sp_operation_fk`) REFERENCES `sprinkler_system_operation` (`id`);

ALTER TABLE `sprinkler_systems` ADD FOREIGN KEY (`sp_presence_fk`) REFERENCES `sprinkler_system_presence` (`id`);

ALTER TABLE `location` ADD FOREIGN KEY (`property_use_fk`) REFERENCES `property_use` (`id`);

ALTER TABLE `incidents_fact_table` ADD FOREIGN KEY (`damages_fk`) REFERENCES `damages` (`id`);

ALTER TABLE `incidents_fact_table` ADD FOREIGN KEY (`fire_alarms_fk`) REFERENCES `fire_alarms` (`id`);

ALTER TABLE `incidents_fact_table` ADD FOREIGN KEY (`tfs_fk`) REFERENCES `toronto_fire_services` (`id`);

ALTER TABLE `incidents_fact_table` ADD FOREIGN KEY (`fire_details_fk`) REFERENCES `fire_details` (`id`);

ALTER TABLE `incidents_fact_table` ADD FOREIGN KEY (`civilian_impact_fk`) REFERENCES `civilian_impact` (`id`);

ALTER TABLE `incidents_fact_table` ADD FOREIGN KEY (`location_fk`) REFERENCES `location` (`id`);

ALTER TABLE `incidents_fact_table` ADD FOREIGN KEY (`sprinkler_systems_fk`) REFERENCES `sprinkler_systems` (`id`);

ALTER TABLE `incidents_fact_table` ADD FOREIGN KEY (`smoke_alarms_fk`) REFERENCES `smoke_alarms` (`id`);


